### PR TITLE
Added example_async file

### PR DESCRIPTION
**Pull request by saimedhi**
Signed-off-by: saimedhi <saimedhi@amazon.com>

### CODE REVIEW

**Comment by saimedhi** [comment]
Hello DB, please let me know if you want any other changes. And also do I need to add this file link in ReadMe.

**Comment by dblock** [comment]
I am surprised you can just run this example under pipenv. Can you? There are likely needed changes in Pipfile for dependencies such as asyncio. Maybe move the existing Pipenv* and example.py into sync/..., add another async/... folder, and document both in README? 

I got further in https://github.com/opensearch-project/opensearch-py/issues/272#issuecomment-1396125032 but didn't finish btw.

**Comment by dblock** [comment]
https://github.com/dblock/opensearch-python-client-demo/commit/5ed7b24a4dce7e4e04ccc4ae68916b718b343333 has working code against opensearch-py HEAD. Needs an extra and asyncio in Pipfile.

If you add a refresh parameter, you'd hit https://github.com/opensearch-project/opensearch-py/pull/274

I'll merge that into this demo once we have serverless working, but feel free to reorganize these samples into maybe 2 directories in this PR if you have time.

**Comment by saimedhi** [comment]
Hello DB, I reorganized samples into sync and async folders and made changes to Readme file. Please let me know if I need to make any other changes.

**Comment by dblock** [comment]
Merged via https://github.com/dblock/opensearch-python-client-demo/commit/49edc2215b02e76b588ed4461d75b264fa1daefa and updated async demo to support serverless, thanks!

**Pull request closed without merging**
